spring.application.name=ss12

# C?u hình thymeleaf

# Ti?n t?
spring.thymeleaf.prefix=classpath:/templates/
# H?u t?
spring.thymeleaf.suffix=.html
# Có l?u tr? t?m th?i hay không
spring.thymeleaf.cache=false

server.port=8386